[project]
name = "european_cloud"
version = "0.1.0"
description = "European Cloud Providers"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx ~= 0.28",
    "boto3 ~= 1.38",
    "pyyaml ~= 6.0",
    "python-dotenv ~= 1.1",
]
